version: "3.9"

services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - api_network
    environment:
      PG_HOST: pg
      PG_PORT: 5432
      PG_USER: ev-chargers
      PG_PASSWORD: ev-chargers  # change on production
      PG_DATABASE: ev-chargers
    depends_on:
      pg:
        condition: service_started
      migrate:
        condition: service_completed_successfully

  migrate:
    image: migrate/migrate
    ports:
      - "8080:8080"
    networks:
      - api_network
    volumes:
      - ./migrations:/migrations
    command: [
      "-path",
      "/migrations",
      "-database",
      "postgres://ev-chargers:ev-chargers@pg:5432/ev-chargers?sslmode=disable",
      "up"
    ]
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgis/postgis:14-3.3-alpine
    ports:
      - "5433:5432"
    networks:
      - api_network
    volumes:
      - ./database:/var/lib/postgresql
    environment:
      POSTGRES_USER: ev-chargers
      POSTGRES_PASSWORD: ev-chargers  # change on production
      POSTGRES_DB: ev-chargers
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ev-chargers" ]
      interval: 5s
      timeout: 5s
      retries: 3

networks:
    api_network:
